# Cosmos REST Faucet configuration

gaia_home_folder = "/mnt/cosmos/rand"
transactions_log = "transactions.csv"
request_timeout    = "86400"

[rand]
prefix         = "cosmos"
denomination   = "urand"

[testnets]
    [testnets.rand-1]
    node_url = "http://localhost:46657"
    chain_id = "rand-1"
    faucet_address = "cosmos1f9k0728rcngqj7p2eeqk27v8dw5sw5ccydx77j"
    daily_cap = "400000000"
    amount_to_send = "10000000"
    tx_fees = "500"
